### PR TITLE
Update for jlab 0.35

### PR DESCRIPTION
**Pull request by jasongrout**
I didn't actually test this, but the package versions are updated and it at least builds.

### CODE REVIEW

**Comment by athornton** [comment]
For what it's worth I have a slightly older version of the same (with some alpha versions in package.json) and it runs just fine.

**Comment by vishnu2kmohan** [comment]
Eagerly awaiting an official release and npm package update so I can unleash JupyterLab 0.35.2 onto our expectant users :grin: :pray:

**Comment by blink1073** [comment]
Published to npm as 0.12.0

**Comment by mrocklin** [comment]
Thanks all

**Pull request merged**
